Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision "file", 
    source: "~/projects/Otomato/webapp.py", destination: "/tmp/webapp.py"
	
  config.vm.provision "shell",
   path: "deployment_script.sh"
end
